[package]
name = "echo-client"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.37.0", features = ["full"] }
rand = "0.8.5"
clap = { version = "4.5.4", features = ["derive"] }
