#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <cstdarg>
#include <cstdint>
#include <cstdlib>
#include <ostream>
#include <new>

namespace arith {

struct Term {
  enum class Tag {
    Lit,
    Neg,
    Add,
  };

  struct Lit_Body {
    int64_t _0;
  };

  struct Neg_Body {
    const Term *_0;
  };

  struct Add_Body {
    const Term *_0;
    const Term *_1;
  };

  Tag tag;
  union {
    Lit_Body lit;
    Neg_Body neg;
    Add_Body add;
  };
};

extern "C" {

const void *parse_ffi_alloc();

void parse_ffi_free_alloc(const void *alloc);

Term *parse_ffi(const void *alloc, const char *s);

} // extern "C"

} // namespace arith
