#pragma once

/* Warning, this file is autogenerated by cbindgen. Don't modify this manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stddef.h>
#include <stdint.h>
#include <stdlib.h>


typedef enum Term_Tag {
  Lit,
  Neg,
  Add,
} Term_Tag;

typedef struct Add_Body {
  const struct Term *_0;
  const struct Term *_1;
} Add_Body;

typedef struct Term {
  Term_Tag tag;
  union {
    struct {
      int64_t lit;
    };
    struct {
      const struct Term *neg;
    };
    Add_Body add;
  };
} Term;

struct Term *parse_ffi(const void *alloc, const char *s);

const void *parse_ffi_alloc(void);

void parse_ffi_free_alloc(const void *alloc);
