# Python
#
# install(DIRECTORY "C:/Python26/libs"  DESTINATION ${CMAKE_RUNTIME_OUTPUT_DIRECTORY} FILES_MATCHING PATTERN)

#Boost

install(DIRECTORY "C:/Boost/lib/" DESTINATION ${CMAKE_RUNTIME_OUTPUT_DIRECTORY} FILES_MATCHING PATTERN "*.dll")


